---
- name: terraform
  block:
    - name: install terraform dependancies
      package:
        name: "{{ item }}"
        state: latest
      register: result
      until: result is succeeded
      with_items:
        - gnupg
        - software-properties-common
        - curl

    - name: add hashicorp gpg key
      shell: curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -

    - name: add hashicorp repo
      shell: apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"

    - name: update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes

    - name: install terraform dependancies
      package:
        name: "terraform"
        state: latest
      register: result
      until: result is succeeded